name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Build Package
        run: |
          corepack enable
          yarn
          yarn build
          yarn workspace infrastry pack --filename infrastry.tgz
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: infrastry-${{ github.sha }}
          path: packages/infrastry/infrastry.tgz
